name: Github Actions test
on: [push]
jobs:
  rspec:
    name: Run rspec
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7.17
    env:
      DB_USERNAME: db_user
      DB_PASSWORD: password
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: bundle install
        run: bundle install
      - name: run rspec
        run: bundle exec rspec
    
