name: Github Actions test
on: [push]
jobs:
  rspec:
    name: Run rspec
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7.17
    env:
      DB_USERNAME: db_user
      DB_PASSWORD: password
      RAILS_ENV: test
      RAILS_DB_HOST: localhost
      RAILS_DB_PASSWORD: ${{ secrets.RAILS_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependent libralies
        run: sudo apt-get install libmysqlclient-dev
      - name: bundle install
        run: |
          gem install bundler
          bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: yarn install
        run: |
          yarn install
          bundle exec bin/webpack
      - name: Run migration
        run: |
          sudo /etc/init.d/mysql start
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run rspec
        run: bundle exec rspec
